services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  user_service:
    build: 
      context: ./user_service
      dockerfile: src/dockerfile
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql/${MYSQL_DATABASE}
      - SECRET_KEY=${SECRET_KEY}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_SSL_VERIFY=${ELASTICSEARCH_SSL_VERIFY}
    depends_on:
      - mysql
      - elasticsearch

  discussion_service:
    build: 
      context: ./discussion_service
      dockerfile: src/dockerfile
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql/${MYSQL_DATABASE}
      - SECRET_KEY=${SECRET_KEY}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_SSL_VERIFY=${ELASTICSEARCH_SSL_VERIFY}
    depends_on:
      - mysql
      - elasticsearch

  comment_service:
    build: 
      context: ./comment_service
      dockerfile: src/dockerfile
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql/${MYSQL_DATABASE}
      - SECRET_KEY=${SECRET_KEY}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_SSL_VERIFY=${ELASTICSEARCH_SSL_VERIFY}
    depends_on:
      - mysql
      - elasticsearch

  like_service:
    build: 
      context: ./like_service
      dockerfile: src/dockerfile
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql/${MYSQL_DATABASE}
      - SECRET_KEY=${SECRET_KEY}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_SSL_VERIFY=${ELASTICSEARCH_SSL_VERIFY}
    depends_on:
      - mysql
      - elasticsearch

  search_service:
    build: 
      context: ./search_service
      dockerfile: src/dockerfile
    environment:
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_SSL_VERIFY=${ELASTICSEARCH_SSL_VERIFY}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - elasticsearch

  api_gateway:
    build: 
      context: ./api_gateway
      dockerfile: src/dockerfile
    depends_on:
      - user_service
      - discussion_service
      - comment_service
      - like_service
      - search_service
    ports:
      - "5000:5000"

volumes:
  mysql_data: